name: "Deploy to Sentry"
description: "Create a Sentry release and deploy source maps"
inputs:
  sentryOrganization:
    description: "What Sentry org to use"
    required: true
  sentryProject:
    description: "What Sentry project to use"
    required: true
  sentryAuthToken:
    description: "Sentry auth token"
    required: true
  releaseId:
    description: "Release ID (usually commit SHA)"
    required: true
  sourceMapLocation:
    description: "Where are the source maps located?"
    required: true
    default: "~/"

runs:
  using: "docker"
  image: "Dockerfile"
