name: "Release and source maps"
description: "Create a release and deploy source maps"
inputs:
  sentryOrganization:
    description: "What org to use"
    required: true
  sentryProject:
    description: "What project to use"
    required: true
  sentryAuthToken:
    description: "Auth token for Sentry"
    required: true
  releaseId:
    description: "Release ID"
    required: true
  sourceMapLocation:
    description: "Where are the source maps located?"
    required: true
    default: "~/"
  sourceMapPrefix:
    description: "Optional prefix for the location of source maps"
    required: false
    default: "~/"
outputs:
  versionId: # id of output
    description: "used version id"
runs:
  using: "docker"
  image: "getsentry/sentry-cli"
  entrypoint: "main.sh"
